name: build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - CC: gcc-7
            CXX: g++-7
            install: g++-7
            artifacts: true
          - CC: clang-5.0
            CXX: clang++-5.0
            install: clang-5.0

    env:
      CC: ${{matrix.CC}}
      CXX: ${{matrix.CXX}}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install compiler
        if: ${{matrix.install}}
        run: sudo apt install ${{matrix.install}}

      - name: Configure stuff
        run: |
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=${{github.workspace}} ..

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: |
          cmake --build . -j 6 --target install
          cd ..
          install -D LICENSE.md share/doc/insomnia-toolset/LICENSE.md
          install -D README.md share/doc/insomnia-toolset/README.md

      - name: Upload Artifacts
        if: ${{matrix.artifacts == true}}
        uses: actions/upload-artifact@v2
        with:
          name: InsomniaToolset-linux-amd64
          path: |
            ${{github.workspace}}/bin
            ${{github.workspace}}/lib
            ${{github.workspace}}/share
          retention-days: 5

  build-widle:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Configure stuff
        run: |
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake -DCMAKE_BUILD_TYPE=Release -A x64 -DCMAKE_INSTALL_PREFIX=${{github.workspace}} ..
      - name: Build
        working-directory: ${{github.workspace}}/build
        run: |
          cmake --build . -j 6 --config Release --target install
          cd ..
          copy LICENSE.md bin/LICENSE.md
          copy README.md bin/README.md

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: InsomniaToolset-win64
          path: |
            ${{github.workspace}}/bin
          retention-days: 5
